# Generated by Django 4.2.6 on 2023-10-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonVegetarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("image_url", models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name="Vegetarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("image_url", models.CharField(max_length=2083)),
            ],
        ),
        migrations.RenameModel(old_name="Product", new_name="Beverages",),
    ]
